// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iaccbdtawauxhowxlgzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhY2NiZHRhd2F1eGhvd3hsZ3p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MDQ2MjMsImV4cCI6MjA2MzI4MDYyM30.2hc1OtgOI8wD4xoXpQOqClZw7VrYQxG8RK6cwDFYNhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);